/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    UserManagement: typeof import('./src/view/admin/UserManagement.vue')['default']
    UserTable: typeof import('./src/view/admin/UserTable.vue')['default']
  }
}
